# SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@liri.io>
#
# SPDX-License-Identifier: CC0-1.0

name: 'qmllint-action'
description: 'Validates QML and JavaScript files'
author: 'plfiorini'

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'